version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app

  db:
    image: 'mysql:latest'
    restart: always
    environment:
      - MYSQL_DATABASE=catalog
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3366:3306

  cache:
    image: 'redis'
    command: redis-server --appendonly yes
    volumes:
      - .redis_data:/data